apiVersion: apps/v1
kind: Deployment
metadata:
  name: gt-image-recognition
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gt-image-recognition
  template:
    metadata:
      namespace: default
      labels:
        app: gt-image-recognition
    spec:
      containers:
      - name: myapp
        image: gtimagerecognition.azurecr.io/gt-image-recognition:83285
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: acr-secret # Reference to the secret you created

---
#########################################################
# Service
#########################################################
apiVersion: v1
kind: Service
metadata:
  name: gt-image-recognition-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: gt-image-recognition
  ports:
    - port: 1111
      protocol: TCP
      targetPort: 5000
